server:
  baseUrl: http://localhost:8080/
  imageUrl: student/images/
  imageServerDir: c:/bitbucket/images/
---
spring:
  profiles: local
server:
  baseUrl: http://localhost:1000/
  imageUrl: images/
---
spring:
  profiles: remote
server:
  baseUrl: https://s3-ap-southeast-1.amazonaws.com/se331/
  imageUrl: pics/